#  _______  _______  __    _  _______  ___   _______
# |       ||       ||  |  | ||       ||   | |       |
# |       ||   _   ||   |_| ||    ___||   | |    ___|
# |       ||  | |  ||       ||   |___ |   | |   | __
# |      _||  |_|  ||  _    ||    ___||   | |   ||  |
# |     |_ |       || | |   ||   |    |   | |   |_| |
# |_______||_______||_|  |__||___|    |___| |_______|

version: "1.0.0-ALPHA"